### ISSUE TITLE
Linux 系统下rar文件解压的问题

### ISSUE THREAD

**Issue by 3zeroed** [sucat1997/unrar5#1]
### 首先我将代码简单改为读取jar包目录下全部rar文件并解压
![image](https://user-images.githubusercontent.com/44516212/140706995-8c2019ce-11e0-47f1-ac81-ef8ad552da43.png)

#### 文件夹\DIM-1内的文件名前无反斜杠
![image](https://user-images.githubusercontent.com/44516212/140706958-875789e7-e1aa-4af2-82df-91b923c7edd3.png)

**Comment by sucat1997** [comment]
我认为可能是路径的问题，我回去帮你看一下，回去做核酸喽

**Comment by sucat1997** [comment]
或许尝试将 斜杠 替换成 类似于 File.separator 的标准格式，因为我没有linux环境

**Comment by sucat1997** [comment]
> ### 首先我将代码简单的读取jar包目录下所有rar文件并解压
> ![图片](https://user-images.githubusercontent.com/44516212/140706995-8c2019ce-11e0-47f1-ac81-ef8ad552da43.png)
> 
> ### 左图为Windows解压后目录，右图为Linux解压后目录
> #### Linux系统解压后只有第一级目录文件夹名和文件名前会出现反斜杠
> #### 文件夹\DIM-1内的文件名前无反反杠
> ![图片](https://user-images.githubusercontent.com/44516212/140706958-875789e7-e1aa-4af2-82df-91b923c7edd3.png)

**Comment by sucat1997** [comment]
> ### 首先我将代码简单的读取jar包目录下所有rar文件并解压
> ![图片](https://user-images.githubusercontent.com/44516212/140706995-8c2019ce-11e0-47f1-ac81-ef8ad552da43.png)
> 
> ### 左图为Windows解压后目录，右图为Linux解压后目录
> #### Linux系统解压后只有第一级目录文件夹名和文件名前会出现反斜杠
> #### 文件夹\DIM-1内的文件名前无反反杠
> ![图片](https://user-images.githubusercontent.com/44516212/140706958-875789e7-e1aa-4af2-82df-91b923c7edd3.png)

我通过修改 斜杠 为 File.separator 来修改这个问题，你可以更新一下代码并检验下是否可行。
ps：关闭评论是误操作，我还没有玩转这个GitHub

**Comment by sucat1997** [comment]
file.separator

**Comment by sucat1997** [comment]
我通过修改 斜杠 为 File.separator 来修改这个问题，你可以更新一下代码并检验下是否可行。
ps：关闭评论是误操作，我还没有玩转这个GitHub

**Comment by sucat1997** [comment]
确认了，就是代码中应该更正为
File file = new File(ourDir + File.separator + path);
