### ISSUE TITLE
可以从rar5压缩包中解压一个指定的文件到指定的路径?

### ISSUE THREAD

**Issue by NanyangTaiji** [sucat1997/unrar5#2]

**Comment by sucat1997** [comment]
可以在遍历中做

**Comment by NanyangTaiji** [comment]
How?

**Comment by sucat1997** [comment]
之前在mian方法里写了，忘记回复了

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
bkrcq, @Miantang, @ihornet, @radaren, @randliu, @chunleiding, @xmjin, @adamwoo, @tyn520215, @ZatDavid, @jblymq, @fengzhibo294, @wangsenyan, @panol, @misty44, @YMSH123, @hdqdev, @xinliangnote, @BingliangChen, @BigJungle-Wj, @haynesxiang, @deembaker, @lixiumingming, @, @GaryMK, @gdxieyue, @xiaoxuh, @cason0126, @GSven, @XieWeiXie, @lipengming, @newjueqi, @CTKnight, @yedy99, @astounded, @lxflxfeng, @wtthard, @phial3, @Liuyanan1801210591, @Floydwish, @Student-Duan, @jatesun, @kaiiang, @limengwei, @xintai777, @jeryz, @gugang, @whyaysd, @learningalways2016, @RichardCRF

**Comment by sucat1997** [comment]
参考 Main 中的 UnCompressUtil.decompress 方法
